### PR TITLE
cruelty squad theme

### PR DESCRIPTION
**Pull request by migabyte**
alr so basically i figured out how to make the two changes in one pull. ignore the patch being called 1a, and also pretend the commit "cruelty squad in themes.js" says "cruelty squad in settings.html". if the pull gets pushed, with permission i will add a couple things more to the theme.

### CODE REVIEW

**Review by migabyte — COMMENTED** [review]
background repeat does not work

**Comment by migabyte** [comment]
font-family does not work

**Comment by proudparrot2** [comment]
uh no offense but this theme isn't very good, I don't think it's a quality addition to make

**Comment by migabyte** [comment]
> uh no offense but this theme isn't very good, I don't think it's a quality addition to make

yeah i know the css is for som e reason different than css that i used for my website, like font families being gone and backgroind repeating disappeared

**Pull request closed without merging**
