### PR TITLE
Update games.js

### PR DESCRIPTION
**Pull request by migabyte**
118 characters replaced in line 23, 1 line added between lines 60 and 61 with 59 characters

### CODE REVIEW

**Comment by proudparrot2** [comment]
What's the point of switching Cookie Clicker source? Is it more stable?

**Comment by migabyte** [comment]
honestly my friends say that version is better than the one you guys currently have, so i figure that more people would like that cookie clicker source than the current one

**Comment by proudparrot2** [comment]
Okay the

**Comment by proudparrot2** [comment]
Okay then

**Comment by migabyte** [comment]
<image src="https://c8.alamy.com/comp/MNNJMP/surprised-emoticon-smiley-MNNJMP.jpg">

**Pull request merged**
