### PR TITLE
small stuff

### PR DESCRIPTION
**Pull request by Rahib777-7**

### CODE REVIEW

**Comment by Rahib777-7** [comment]
just  made some small ui changes

**Comment by mdoryammilwalrus** [comment]
This removes the vanity link...

**Comment by Asleep123** [comment]
whole point
what if it expires

**Comment by Rahib777-7** [comment]
> This removes the vanity link...

you need to give discord money for vanity

**Comment by thewilloftheshadow** [comment]
> > This removes the vanity link...
> 
> you need to give discord money for vanity

The server has 29 boosts, there's no danger of that for a long time to come

**Comment by Asleep123** [comment]
waiting for clearance from parrot so no merge conflict

**Pull request merged**
