### PR TITLE
theme 2

### PR DESCRIPTION
**Pull request by migabyte**
mb i didnt know i had to change this too

### CODE REVIEW

**Comment by proudparrot2** [comment]
oh joy 
image

**Comment by migabyte** [comment]
> oh joy image

the two things are in different pull requests cuz i forgot to change this on the first pull i did regarding the theme

**Comment by Asleep123** [comment]
isn’t this just light theme..

**Comment by proudparrot2** [comment]
> isn’t this just light theme..

No, he didn't configure smth right

@migabyte, could you put it into one pr?

**Comment by migabyte** [comment]
> > isn’t this just light theme..
> 
> No, he didn't configure smth right
> 
> @migabyte, could you put it into one pr?

yeah i was just clumsy and forgot to do that on the first pr, sorry

**Comment by proudparrot2** [comment]
Could you do a new one now?

**Comment by migabyte** [comment]
> Could you do a new one now?

sure, in a bit

**Pull request closed without merging**
